[tool.poetry]
name = "polymatheia-tools"
version = "0.1.0"
description = "A Python package that provides useful scripts for working with data loaded using the Polymatheia library."
authors = ["Andreas LÃ¼schow <lueschow@sub.uni-goettingen.de>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
progress = "^1.6"
polymatheia = "^0.3.1"
loguru = "^0.5.3"
matplotlib = "^3.4.3"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
