[tool.poetry]
name = "testing_pypi"
version = "v5.6"
description = "testing stuff w/ poetry"
readme = "README.md"
authors = ["cbonafin"]
license = "MIT"
repository = "https://github.com/cbonafin"
keywords = ["test"]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.3.0"
fire = "0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
