[tool.poetry]
name = "combinatorial_gwas"
version = "0.2.0"
description = "A package for the final project of MIT's 6.874 class Deep Learning in Life Science"
authors = ["anhoang <anhoang@wi.mit.edu>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.9"
keras-tuner = "^1.0.2"
bgen-reader = "^4.0.7"
requests = "^2.25.1"
aiohttp = "^3.7.4"
pydantic = "^1.8.1"
fastparquet = "^0.5.0"
hydra-core = "1.1.0.dev5"
shap = "^0.39.0"
deeplift = "^0.6.13"
matplotlib = "^3.4.1"
seaborn = "^0.11.1"
umap-learn = "^0.5.1"
apricot-select = "^0.6.1"
pca = "^1.4.0"
pandas = "^1.2.4"
datashader = "^0.12.1"
bokeh = "^2.3.1"
holoviews = "^1.14.3"
scikit-image = "^0.18.1"
colorcet = "^2.0.6"
statsmodels = "^0.12.2"


[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
jupyterlab = "^3.0.12"
ipython = "7.10"
jedi = "0.17.2"
nbdev = "^1.1.13"
plotly = "^4.14.3"
pandas = "^1.2.3"
kedro = "^0.17.2"
tqdm = "^4.59.0"
portray = "^1.5.2"
twine = "^3.4.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
