[tool.poetry]
name = "sinaspider"
version = "0.2.0"
description = ""
authors = ["Bao Hengtao <baohengtao@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
lxml = "^4.6.3"
loguru = "^0.5.3"
pendulum = "^2.1.2"
psycopg2 = "^2.9.1"
dataset = "^1.5.0"
python-baseconv = "^1.2.2"
PyExifTool = "^0.4.11"


[tool.poetry.dev-dependencies]
jupyterlab = "*"
JLDracula = "*"
jupyterlab_vim = "*"
ptpython = "*"
jupyterlab-lsp = "*"
python-lsp-server = "^1.2.1"
Sphinx = "^4.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
